"use client";

import { useState, useRef } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Input, Textarea, Select } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";
import { Upload, X, Image as ImageIcon, ArrowRight, Sparkles, CheckCircle, ShieldCheck, Zap } from "lucide-react";
import type { Metadata } from "next";

const tshirtTypes = [
  { value: "oversized", label: "Oversized T-shirt" },
  { value: "regular", label: "Regular Fit T-shirt" },
  { value: "polo", label: "Polo / Collar T-shirt" },
  { value: "hoodie", label: "Hoodie / Sweatshirt" },
  { value: "jersey", label: "Sports Jersey" },
  { value: "other", label: "Other (mention in description)" },
];

const printPlacements = [
  { value: "front", label: "Front only" },
  { value: "back", label: "Back only" },
  { value: "front-back", label: "Front + Back" },
  { value: "full-print", label: "Full print (All-over)" },
  { value: "sleeve", label: "Sleeve print" },
  { value: "other", label: "Other" },
];

const budgetRanges = [
  { value: "under-300", label: "Under ₹300/piece" },
  { value: "300-500", label: "₹300 – ₹500/piece" },
  { value: "500-800", label: "₹500 – ₹800/piece" },
  { value: "800-1200", label: "₹800 – ₹1200/piece" },
  { value: "above-1200", label: "Above ₹1200/piece" },
  { value: "flexible", label: "Flexible — advise me" },
];

export default function CustomRequestPage() {
  const router = useRouter();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [form, setForm] = useState({
    title: "",
    description: "",
    tshirt_type: "",
    preferred_colors: "",
    print_placement: "",
    quantity: "1",
    budget_range: "",
    deadline: "",
  });
  const [images, setImages] = useState<File[]>([]);
  const [imagePreviews, setImagePreviews] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [consent, setConsent] = useState(false);

  const handleChange = (field: string, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handleFileSelect = (files: FileList | null) => {
    if (!files) return;
    const newFiles = Array.from(files).slice(0, 5 - images.length);
    const newPreviews = newFiles.map((f) => URL.createObjectURL(f));
    setImages((prev) => [...prev, ...newFiles]);
    setImagePreviews((prev) => [...prev, ...newPreviews]);
  };

  const removeImage = (index: number) => {
    setImages((prev) => prev.filter((_, i) => i !== index));
    setImagePreviews((prev) => prev.filter((_, i) => i !== index));
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    handleFileSelect(e.dataTransfer.files);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!consent) {
      setError("Please confirm that your reference images are copyright-free or owned by you.");
      return;
    }

    setLoading(true);
    setError("");

    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();

    // Upload reference images
    let imageUrls: string[] = [];
    if (images.length > 0 && user) {
      const uploads = await Promise.all(
        images.map(async (file, idx) => {
          const ext = file.name.split(".").pop();
          const path = `design-requests/${user.id}/${Date.now()}-${idx}.${ext}`;
          const { data, error: uploadError } = await supabase.storage
            .from("design-files")
            .upload(path, file, { upsert: false });
          if (uploadError) return null;
          const { data: { publicUrl } } = supabase.storage
            .from("design-files")
            .getPublicUrl(path);
          return publicUrl;
        })
      );
      imageUrls = uploads.filter(Boolean) as string[];
    }

    // Insert design request
    const { data: request, error: insertError } = await supabase
      .from("design_requests")
      .insert({
        user_id: user?.id ?? null,
        title: form.title,
        description: form.description,
        reference_images: imageUrls,
        tshirt_type: form.tshirt_type,
        preferred_colors: form.preferred_colors,
        print_placement: form.print_placement,
        quantity: parseInt(form.quantity) || 1,
        budget_range: form.budget_range,
        deadline: form.deadline || null,
        tracking_code: "", // auto-generated by DB trigger
      })
      .select()
      .single();

    if (insertError) {
      setError("Failed to submit request. Please try again or contact us on WhatsApp.");
      setLoading(false);
      return;
    }

    router.push(`/custom-request/success?code=${request.tracking_code}&id=${request.id}`);
  };

  return (
    <div className="min-h-screen bg-[#FAF9F6] text-[#141414] font-sans">
      
      {/* Dark Hero Section */}
      <section className="py-20 bg-[#121212] text-white relative overflow-hidden border-b border-white/10">
        {/* Background Watermark */}
        <div className="absolute inset-0 pointer-events-none select-none overflow-hidden flex items-center justify-center z-0">
          <span className="text-[22vw] font-black tracking-tighter text-white/[0.02] uppercase leading-none font-mono">
            CUSTOM
          </span>
          <div className="absolute w-[500px] h-[500px] bg-[#F05A22]/15 rounded-full blur-[160px]" />
        </div>

        <div className="relative z-10 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-4">
          <div className="inline-flex items-center gap-2 bg-[#F05A22]/15 border border-[#F05A22]/30 text-[#F05A22] rounded-full px-4.5 py-1.5 text-xs font-mono font-bold uppercase tracking-widest">
            <Sparkles className="w-3.5 h-3.5" /> Kochi Studio Briefing
          </div>
          <h1 className="text-4xl sm:text-6xl font-black uppercase tracking-tight text-white leading-none">
            WORK DIRECTLY WITH A <span className="text-[#F05A22]">KOCHI DESIGNER</span>
          </h1>
          <p className="text-white/70 text-base sm:text-lg max-w-xl mx-auto font-medium">
            Upload reference images or describe your idea. A specialist graphic designer will craft 300 DPI vector concepts for your approval.
          </p>
        </div>
      </section>

      {/* Main Form Stage */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid lg:grid-cols-12 gap-8 items-start">
          
          {/* Left: Interactive Form (8 cols) */}
          <div className="lg:col-span-8">
            <form onSubmit={handleSubmit} className="space-y-8">
              
              {/* 1. Basic Info Card */}
              <div className="bg-white rounded-[24px] border border-[#EAEAEA] p-8 sm:p-10 space-y-6 shadow-xl shadow-black/[0.03]">
                <div className="flex items-center justify-between border-b border-[#EAEAEA] pb-4">
                  <h2 className="font-black text-[#141414] text-xl uppercase tracking-tight flex items-center gap-2">
                    <span className="w-7 h-7 rounded-xl bg-[#F05A22] text-white flex items-center justify-center text-xs font-mono">01</span>
                    About Your Design Brief
                  </h2>
                  <span className="text-xs font-mono text-[#666666] font-bold">REQUIRED</span>
                </div>

                <Input
                  label="Request Title"
                  id="request-title"
                  value={form.title}
                  onChange={(e) => handleChange("title", e.target.value)}
                  placeholder="e.g. MEC Thrissur College Fest 2025 Coordinator Tees"
                  required
                />

                <Textarea
                  label="Describe Your Idea"
                  id="request-description"
                  value={form.description}
                  onChange={(e) => handleChange("description", e.target.value)}
                  placeholder="Describe your design vision — theme, text, graphic elements, layout, mood. The more detail, the better the initial vector proof."
                  required
                  className="min-h-[140px]"
                />

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <Select
                    label="T-shirt Fit / Type"
                    id="tshirt-type"
                    options={tshirtTypes}
                    value={form.tshirt_type}
                    onChange={(e) => handleChange("tshirt_type", e.target.value)}
                    placeholder="Select apparel type..."
                    required
                  />
                  <Select
                    label="Print Placement"
                    id="print-placement"
                    options={printPlacements}
                    value={form.print_placement}
                    onChange={(e) => handleChange("print_placement", e.target.value)}
                    placeholder="Select placement..."
                  />
                </div>

                <Input
                  label="Preferred Colors (optional)"
                  id="preferred-colors"
                  value={form.preferred_colors}
                  onChange={(e) => handleChange("preferred_colors", e.target.value)}
                  placeholder="e.g. Pitch Black tee with Orange + White print"
                />
              </div>

              {/* 2. Reference Images Upload Card */}
              <div className="bg-white rounded-[24px] border border-[#EAEAEA] p-8 sm:p-10 shadow-xl shadow-black/[0.03] space-y-5">
                <div className="flex items-center justify-between border-b border-[#EAEAEA] pb-4">
                  <h2 className="font-black text-[#141414] text-xl uppercase tracking-tight flex items-center gap-2">
                    <span className="w-7 h-7 rounded-xl bg-[#F05A22] text-white flex items-center justify-center text-xs font-mono">02</span>
                    Upload Reference Images
                  </h2>
                  <span className="text-xs font-mono text-[#666666]">MAX 5 FILES</span>
                </div>
                <p className="text-sm text-[#666666] font-medium">
                  Upload sketches, logo files, or inspiration screenshots (PNG, JPG, PDF up to 10MB each).
                </p>

                {/* Drop Zone */}
                <div
                  onDrop={handleDrop}
                  onDragOver={(e) => e.preventDefault()}
                  onClick={() => fileInputRef.current?.click()}
                  className="border-2 border-dashed border-[#EAEAEA] hover:border-[#F05A22] bg-[#FAF9F6] hover:bg-[#F05A22]/5 rounded-2xl p-10 text-center cursor-pointer transition-all group"
                >
                  <Upload className="w-10 h-10 text-[#666666] group-hover:text-[#F05A22] mx-auto mb-3 transition-colors" />
                  <p className="font-black text-[#141414] text-sm uppercase tracking-wider">Drag & Drop Reference Files Here</p>
                  <p className="text-xs text-[#666666] mt-1 font-mono">or click to browse from device</p>
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    accept="image/*,.pdf"
                    className="hidden"
                    onChange={(e) => handleFileSelect(e.target.files)}
                  />
                </div>

                {/* Previews */}
                {imagePreviews.length > 0 && (
                  <div className="flex flex-wrap gap-3 mt-4">
                    {imagePreviews.map((preview, i) => (
                      <div key={i} className="relative w-24 h-24 rounded-2xl overflow-hidden border border-[#EAEAEA] shadow-md group">
                        <img src={preview} alt="" className="w-full h-full object-cover" />
                        <button
                          type="button"
                          onClick={() => removeImage(i)}
                          className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity"
                        >
                          <X className="w-5 h-5 text-white" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* 3. Specs & Deadline Card */}
              <div className="bg-white rounded-[24px] border border-[#EAEAEA] p-8 sm:p-10 space-y-6 shadow-xl shadow-black/[0.03]">
                <div className="flex items-center justify-between border-b border-[#EAEAEA] pb-4">
                  <h2 className="font-black text-[#141414] text-xl uppercase tracking-tight flex items-center gap-2">
                    <span className="w-7 h-7 rounded-xl bg-[#F05A22] text-white flex items-center justify-center text-xs font-mono">03</span>
                    Quantity & Budget Specs
                  </h2>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                  <Input
                    label="Estimated Quantity (pieces)"
                    id="quantity"
                    type="number"
                    min="1"
                    value={form.quantity}
                    onChange={(e) => handleChange("quantity", e.target.value)}
                    required
                  />
                  <Input
                    label="Target Deadline (optional)"
                    id="deadline"
                    type="date"
                    value={form.deadline}
                    onChange={(e) => handleChange("deadline", e.target.value)}
                    min={new Date().toISOString().split("T")[0]}
                  />
                </div>

                <Select
                  label="Budget Range (per piece)"
                  id="budget-range"
                  options={budgetRanges}
                  value={form.budget_range}
                  onChange={(e) => handleChange("budget_range", e.target.value)}
                  placeholder="Select budget range..."
                />
              </div>

              {/* Consent & Error */}
              <div className="bg-white rounded-[24px] border border-[#EAEAEA] p-6 shadow-md">
                <label className="flex items-start gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    id="consent"
                    checked={consent}
                    onChange={(e) => setConsent(e.target.checked)}
                    className="mt-1 w-4 h-4 accent-[#F05A22] cursor-pointer"
                  />
                  <span className="text-xs text-[#666666] leading-relaxed font-medium">
                    I confirm that the reference images uploaded are owned by me or copyright-free. I authorise DesignMyTee to create vector artwork inspired by this brief.
                  </span>
                </label>
              </div>

              {error && (
                <div className="bg-red-50 border border-red-200 text-red-700 text-sm px-6 py-4 rounded-2xl font-medium">
                  {error}
                </div>
              )}

              <Button
                type="submit"
                size="lg"
                loading={loading}
                className="w-full bg-[#F05A22] hover:bg-[#C8461A] text-white font-black text-sm uppercase tracking-wider py-4 rounded-full shadow-xl shadow-[#F05A22]/20"
                icon={<ArrowRight className="w-5 h-5" />}
                iconPosition="right"
              >
                Submit Custom Request
              </Button>
            </form>
          </div>

          {/* Right: Kochi Studio Guarantee Sidebar (4 cols) */}
          <div className="lg:col-span-4 space-y-6">
            
            {/* Live Studio Card */}
            <div className="bg-[#121212] text-white rounded-[24px] border border-white/10 p-7 space-y-5 shadow-2xl relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-[#F05A22]/10 rounded-full blur-3xl pointer-events-none" />
              
              <div className="inline-flex items-center gap-2 bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-full px-3.5 py-1 text-[10px] font-mono font-bold">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                KOCHI PRINT STUDIO ONLINE
              </div>

              <h3 className="text-2xl font-black uppercase tracking-tight leading-snug">
                WHAT HAPPENS AFTER YOU SUBMIT?
              </h3>

              <div className="space-y-4 text-xs font-mono text-white/80">
                {[
                  { step: "01", title: "Human Designer Assigned", desc: "A graphic designer reviews your brief within 2 hours." },
                  { step: "02", title: "3D Digital Proof", desc: "HD 3D vector artwork uploaded to your request dashboard." },
                  { step: "03", title: "Unlimited Tweaks", desc: "Request adjustments until the design is 100% approved." },
                ].map((s) => (
                  <div key={s.step} className="bg-white/5 border border-white/10 p-3.5 rounded-xl space-y-1">
                    <span className="text-[#F05A22] font-bold text-[11px] block">// PHASE {s.step}</span>
                    <p className="font-bold text-white">{s.title}</p>
                    <p className="text-white/60 text-[11px]">{s.desc}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Guarantees Box */}
            <div className="bg-white rounded-[24px] border border-[#EAEAEA] p-7 space-y-4 shadow-xl shadow-black/[0.03]">
              <h4 className="font-black text-[#141414] text-base uppercase tracking-tight flex items-center gap-2">
                <ShieldCheck className="w-5 h-5 text-[#F05A22]" /> Studio Guarantees
              </h4>
              <ul className="space-y-3 text-xs text-[#666666] font-medium">
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-emerald-600 flex-shrink-0" />
                  <span>300 DPI Vector Artwork Setup Included</span>
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-emerald-600 flex-shrink-0" />
                  <span>Fabric GSM & Printing Method Calibration</span>
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-emerald-600 flex-shrink-0" />
                  <span>Doorstep Delivery Pan-India</span>
                </li>
              </ul>
            </div>

          </div>

        </div>
      </div>

    </div>
  );
}
